admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
endpoints_repository: j:\my drive\upf\projects\dst\toxtrust\endpoints
homepage: homepage@domain.org
provider: My Organization
toxtrust_repository: j:\my drive\upf\projects\dst\toxtrust
