name: dst
channels:
  - default
  - rdkit
  - conda-forge
dependencies:
  - more-itertools
  - pip
  - python
  - scikit-learn
  - scipy
  - setuptools
  - pip:
    - ipython
    - matplotlib
    - numpy
    - pandas
    - pyyaml
    - rdkit
    - sklearn
    - xlsxwriter
    - tqdm
    - cirpy
